# Generated by Django 2.2.7 on 2020-01-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_cautela', models.DateTimeField(auto_now=True)),
                ('data_de_devolucao', models.DateTimeField()),
                ('aprovado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='cadastro.Cadastro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerente', to='cadastro.Cadastro')),
            ],
            options={
                'verbose_name_plural': 'Cautela',
            },
        ),
    ]
