# Generated by Django 2.2.7 on 2020-01-28 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cautela', '0002_auto_20200128_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
