# Generated by Django 2.2.7 on 2020-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiais'},
        ),
        migrations.AddField(
            model_name='material',
            name='consumo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
