# Generated by Django 2.2.7 on 2020-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissao', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='permissao',
            field=models.ManyToManyField(to='permissao.Permissao'),
        ),
    ]
